### ISSUE TITLE
User cần thêm API

### ISSUE THREAD

**Issue by nphuonha2101** [hinerumasato/android-blog-api#2]
User cần thêm 2 API

1. `getByUsername`:
 - Path: `/users/{username}`
 - Method: `GET`
 - Return value: **User**
 
2. `getByEmail`:
 - Path: `/users/{email}`
 - Method: `GET`
 - Return value: **User**

**Comment by hinerumasato** [comment]
Ok, can be release in tomorrow

**Comment by nphuonha2101** [comment]
Thank you!

**Comment by hinerumasato** [comment]
Change path to: `/users?username=value1&fullName=value2&....`
**Because the upper path is conflicted with ** `/users/:id`
